/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideNav: typeof import('./src/components/pc/asideNav/AsideNav.vue')['default']
    AsideNavItem: typeof import('./src/components/pc/asideNav/AsideNavItem.vue')['default']
    AsideNavItemGroup: typeof import('./src/components/pc/asideNav/AsideNavItemGroup.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuGroup: typeof import('element-plus/es')['ElMenuGroup']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElPopper: typeof import('element-plus/es')['ElPopper']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpCollectionTag: typeof import('~icons/ep/collection-tag')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpHelp: typeof import('~icons/ep/help')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpNotebook: typeof import('~icons/ep/notebook')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IEpSun: typeof import('~icons/ep/sun')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    ResizableMutiColumn: typeof import('./src/components/pc/resizableMutiColumn/ResizableMutiColumn.vue')['default']
    ResizableMutiColumnItem: typeof import('./src/components/pc/resizableMutiColumn/ResizableMutiColumnItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
